apiVersion: v1
kind: Service
metadata:
  name: skaffold-playgroud-app
  labels:
    app: skaffold-playgroud-app
spec:
  clusterIP: None
  ports:
    - port: 3000
      name: skaffold-playgroud-app
  selector:
    app: skaffold-playgroud-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-playgroud-app
  labels:
    app: skaffold-playgroud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffold-playgroud-app
  template:
    metadata:
      labels:
        app: skaffold-playgroud-app
    spec:
      containers:
      - name: skaffold-playgroud-app
        image: skaffold-playgroud-app
        ports:
        - containerPort: 3000